### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.systeminfo#12]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/frankjoke/ioBroker.systeminfo

- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E115] No license found in io-package.json
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E301] Tests on Travis-ci.org are broken. Please fix.
- [ ] [E801] No repository about text found. Please go to "https://github.com/frankjoke/ioBroker.systeminfo", press the settings button beside the about title and add the description.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/frankjoke/ioBroker.systeminfo", press the settings button beside the about title and add some topics.
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Frank Joke <frankjoke@hotmail.com>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Frank Joke <frankjoke@hotmail.com>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by frankjoke** [comment]
I will go on retirement on April 1st and start to work/ update all adapters. I may need help then because 1 year passed and many things seem to be changed.

**Comment by mcm1957** [comment]
outdated

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
