### ISSUE TITLE
calculate with values using Convert json

### ISSUE THREAD

**Issue by Fiiti** [iobroker-community-adapters/ioBroker.systeminfo#15]
Hi,
as first many thanks for this work! Very cool, very usable, very good! Respect!

My question:
I wonder if it would possible to calculate with the JSON convert directly?

I perform a Web-API Call and receive a json back.
With the RegEx Filter II pick up only the wished value. Everything okay.
But, I get e. g. a value of 1536, but I would like to store the Value 153.6.

So I wonder if this would possible?

Regards,
Fi

**Comment by mcm1957** [comment]
outdated
