### ISSUE TITLE
Fehlermeldungen des Adapters "Systeminfo" 

### ISSUE THREAD

**Issue by WillyIoBrok** [iobroker-community-adapters/ioBroker.systeminfo#26]
ioBroker

Systemdata | Bitte Ausfüllen
-- | --
Hardwaresystem: | Pi4
Arbeitsspeicher: | 4GB
Festplattenart: | SD-Karte
Betriebssystem: | Linux ioBroker image
Node-Version: | ?
Nodejs-Version: | 10.17.0
NPM-Version: | 6.11.3
Installationsart: | Skript
Image genutzt: | Ja
Ort/Name der Imagedatei: | ?

Hallo, mir ist vor kurzem aufgefallen, daß ich rote Einträge im Log habe. Die kommen ausschliesslich im Zusammenhang mit dem Adapter Systeminfo.
Ich brauche diesen Adapter nicht unbedingt, ich habe ihn deshalb disabled (dann sind die Meldungen weg), aber ich bin mir nicht sicher, ob diese Fehlermeldungen nicht auch von einer möglicherweise korrupten SD-Karte hervorgerufen werden können - deshalb stelle ich mal die Frage hier in's Forum, vielleicht kennt ja jemand ide Ursache.

Grüße,

WillyIoBrok

ioBroker-Log:

host.ioBroker-4	2021-03-15 11:42:14.967	info	instance system.adapter.systeminfo.0 terminated with code 0 (NO_ERROR)
host.ioBroker-4	2021-03-15 11:42:14.965	error	Caught by controller[0]: Segmentation fault
systeminfo.0	2021-03-15 11:42:14.405	info	(7059) Terminated (NO_ERROR): Without reason
systeminfo.0	2021-03-15 11:42:14.404	info	(7059) terminating
systeminfo.0	2021-03-15 11:42:14.324	error	(7059) Error: Command failed: route 2>/dev/null | grep default | awk '{print $8}' Segmentation fault at checkExecSyncError (child_process.js:629:11) at execSync (child_process.js:666:13)
systeminfo.0	2021-03-15 11:42:14.323	error	(7059) uncaught exception: Command failed: route 2>/dev/null | grep default | awk '{print $8}' Segmentation fault
systeminfo.0	2021-03-15 11:42:12.108	warn	(7059) Error TypeError: Cannot read property 'toString' of null in doPoll for HP_Photosmart_7520.[name/value]
systeminfo.0	2021-03-15 11:42:10.698	warn	(7059) Error TypeError: Cannot read property 'toString' of null in doPoll for System.Led_Red
systeminfo.0	2021-03-15 11:42:10.695	warn	(7059) Error TypeError: Cannot read property 'toString' of null in doPoll for System.Led_Green
systeminfo.0	2021-03-15 11:42:10.662	warn	(7059) Used invalid characters: systeminfo.0.NAS.Space_? changed to systeminfo.0.NAS.Space__
systeminfo.0	2021-03-15 11:42:10.551	info	(7059) Startup Systeminfo Adapter systeminfo.0: { startup: '#\ngpio mode 1 output\n#rpi: echo none >/sys/class/leds/led0/trigger\necho none >/sys/class/leds/green_led/trigger', items: [ { name: '
systeminfo.0	2021-03-15 11:42:08.905	warn	(7059) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!
systeminfo.0	2021-03-15 11:42:08.874	info	(7059) starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.systeminfo, node: v10.17.0, js-controller: 3.1.6
host.ioBroker-4	2021-03-15 11:42:06.887	info	instance system.adapter.systeminfo.0 started with pid 7059
host.ioBroker-4	2021-03-15 11:41:36.833	info	Restart adapter system.adapter.systeminfo.0 because enabled
host.ioBroker-4	2021-03-15 11:41:36.832	info	instance system.adapter.systeminfo.0 terminated with code 0 (NO_ERROR)

**Comment by mcm1957** [comment]
Please recheck with actual release 1.0.0 and create new issue if problem s still exist.
