### ISSUE TITLE
Neuer JS Controller Update

### ISSUE THREAD

**Issue by Trunks1982** [iobroker-community-adapters/ioBroker.systeminfo#39]
Nach dem Update auf js 4.0.15 kam dieser Fehler
![Bildschirmfoto 2022-02-26 um 00 30 30](https://user-images.githubusercontent.com/62701386/155816731-88a0d934-d306-4f9f-a5c0-b6d15dc8623a.png)

Müsste in der nächsten Version berichtigt werden.

**Comment by stephan1827** [comment]
Any update on this?

**Comment by Tottback** [comment]
Same issue here. I use the adapter to set GPIO pin. 

Seems to be related to this [https://github.com/frankjoke/ioBroker.radar2/issues/43] from same author

> In controller 4 this warning will throw, so could you please ensure, that it gets fixed and create a new release. You can simply replace
> 
> [ioBroker.radar2/fjadapter-core.js](https://github.com/frankjoke/ioBroker.radar2/blob/f3708e9b72a62fe4aba49142e387ba8d5b95d9f9/fjadapter-core.js#L327)
> 
> Line 327 in [f3708e9](https://github.com/frankjoke/ioBroker.radar2/commit/f3708e9b72a62fe4aba49142e387ba8d5b95d9f9)
> 
>  this.c2p(adapter.objects.getObjectList).bind(adapter.objects); 
> by adapter.getObjectList

**Comment by silmaril42** [comment]
I have exactly the same issue after updating ioBroker and the JS controller.

What helped in my case:
in file `/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js`
change line 44 from
`this.getObjectList = this.c2p(adapter.objects.getObjectList).bind(adapter.objects);`
to
`this.getObjectList = this.c2p(adapter.getObjectList).bind(adapter.objects);`

(The change proposed by @Tottback seemed to solve some problems, but that only led to error messages a little bit later in the process. My change solves the issue completely - at least for my setup.)

I'd love to see a fix release soon, even if it's just this tiny change :smiley:

**Comment by tetzlav** [comment]
The Issue seems allready be fixed. If i installad the "github-master" version, this adapater works fine again.
@frankjoke: Can you please publish a new release?

**Comment by mcm1957** [comment]
please verify with release 1.0.0

**Comment by mcm1957** [comment]
should be fixed with 1.0.0
Please create new issue if problems persist.
